

services:
  backend:
    build:
      context: .
    container_name: inventory-backend
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-dev}
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    env_file:
      - .env
    command: mvn spring-boot:run

  frontend:
    image: node:20
    container_name: inventory-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    command: npm run dev

