spring:
  datasource:
    url: ${DB_URL}?TNS_ADMIN=${TNS_ADMIN}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true
        '[use_sql_comments]': true
        dialect: org.hibernate.dialect.OracleDialect
        '[default_schema]': ADMIN
 
logging:
    level:
      root: DEBUG
      '[org.hibernate.SQL]': DEBUG
      '[org.hibernate.type.descriptor.sql.BasicBinder]': TRACE
    file:
      name: logs/dev-application.log
    logback:
      rollingpolicy:
        max-file-size: 10MB
        max-history: 7
server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
