# =============================================
# Spring Boot - Global Shared Configuration
# This file provides default values and shared settings
# across all environments (dev, test, prod)
# =============================================

spring:
  profiles:
    # Do NOT force a default active profile here.
    # Let CI/Dev/Prod set SPRING_PROFILES_ACTIVE explicitly.
    active: # none

  datasource:
    url: ${DB_URL}                              # Fallback (usually overridden by profile-specific config)
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: oracle.jdbc.OracleDriver

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID}      # These values are injected via secrets or env vars
            client-secret: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

  jpa:
    hibernate:
      ddl-auto: none                            # Do not auto-create schemas by default
    show-sql: true                              # Shown unless overridden (e.g. turned off in prod)

  main:
    allow-bean-definition-overriding: true      # Useful when using multiple configs (e.g., testing mocks)

server:
  port: 8081                                     # Default server port
  address: 0.0.0.0                               # Listen on all interfaces
  forward-headers-strategy: framework            # Respect X-Forwarded-* headers from proxies
  servlet:
    session:
      cookie: 
        same-site: none                              # Allow cookies in cross-site requests (adjust as needed)
        secure: true                                 # Use secure cookies (set to false in dev if not using HTTPS)

logging:
  level:
    '[org.springframework.jdbc.core]': DEBUG     # Enable detailed JDBC logs for dev/debugging
    '[org.hibernate.SQL]': DEBUG                 # Hibernate SQL logging (override in prod)

# -------- App-level knobs used by SecurityConfig & SuccessHandler --------
app:
  # Global default: demo OFF. In PROD you can flip with APP_DEMO_READONLY=true
  demo-readonly: ${APP_DEMO_READONLY:false}

  frontend:
    # Defaults make login testable WITHOUT a frontend:
    # after Google login, redirect to backend /api/me which returns JSON profile.
    base-url: ${APP_FRONTEND_BASE_URL:https://localhost:5173}
    landing-path: /auth  # After login, redirect here (frontend route)