# ============================================
# Spring Boot - Test Environment Config
# Profile: test
# Used for unit, integration, and CI testing
# ============================================

spring:
  datasource:
    url: jdbc:h2:mem:testdb         # In-memory H2 database for fast, isolated testing
    driver-class-name: org.h2.Driver
    username: sa                    # Default H2 username
    password:                       # No password required for in-memory use

  jpa:
    hibernate:
      ddl-auto: create-drop       # Create schema on startup, drop it on shutdown
    show-sql: true                # Log all executed SQL statements (useful for debugging)
    properties:
      hibernate:
        '[format_sql]': true      # Format SQL for easier reading in logs

  h2:
    console:
      enabled: true               # Enable browser-based H2 console for debugging
      path: /h2-console           # Accessible at /h2-console (only in local/test environments)

logging:
  file:
    name: logs/test-application.log  # Log file for test runs
  level:
    root: DEBUG                    # Verbose logging for test diagnostics

server:
  port: 8081                       # Ensure consistent port for testing environments

management:
  endpoints:
    web:
      exposure:
        include: health            # Allow health check exposure in test profile
  endpoint:
    health:
      show-details: always         # Always show detailed health info (for CI assertions)

# Overrides schema for H2 tests (used in @Tavle(schema = "$(USERS_SCHEMA:ADMIN)")) 
# warning: This is a placeholder and should be replaced with actual schema name in production.