# =============================================
# Spring Boot - Production Environment Config
# Profile: prod
# Used in deployment (e.g. Docker, cloud, prod server)
# =============================================

# Note: avoid hardcoding secrets here; use environment variables or secret management

spring:
  datasource:
    url: ${DB_URL}                             # Use environment variable for Oracle Wallet path
    username: ${DB_USER}                       # Set via GitHub secrets or secure env injection
    password: ${DB_PASS}
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      connection-timeout: 5000                 # 5 seconds connection timeout
      validation-timeout: 3000                 # 3 seconds validation timeout

  jpa:
    hibernate:
      ddl-auto: update                         # Note: Use Flyway/Liquibase in real enterprise apps
    show-sql: false                            # Disable SQL logging for performance and security
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID}         # Provided via secrets in CI/CD or vault
            client-secret: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

            scope:
              - openid
              - profile
              - email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

server:
  port: 8081                                       # Override default port (if needed by reverse proxy/load balancer)
  forward-headers-strategy: framework              # Use framework strategy to respect X-Forwarded-* headers from proxies
  servlet:
    session:
      cookie:
        same-site: none                      # Allow cross-site cookies for OAuth2
        secure: true                        # Ensure cookies are secure (HTTPS only)

logging:
  level:
    '[com.smartsupplypro]': INFO                           # Application logs: keep informative, not verbose
    root: INFO                                             # Suppress framework-level noise unless needed

management:
  endpoints:
    web:
      exposure:
        include: health                           # Only expose health endpoint publicly
  endpoint:
    health:
      show-details: never                         # Hide internals in production for security reasons

# -------- App-level (prod) --------
app:
  # Flip ON in Fly by setting APP_DEMO_READONLY="true" (kept off by default)
  demo-readonly: ${APP_DEMO_READONLY:false}

  frontend:
    # Real frontend domain for recruiters
    base-url: ${APP_FRONTEND_BASE_URL:https://inventory-service.koyeb.app}
    # Your SPA login landing (matches your success handler)
    landing-path: /auth  # After login, redirect here (frontend route)
