# ============================================
# Spring Boot - Test Environment Config
# Profile: test
# Used for unit, integration, and CI testing
# ============================================

spring:
  datasource:
    # Oracle-compat mode + keep DB alive for the test JVM
    url: jdbc:h2:mem:ssp;MODE=Oracle;DATABASE_TO_UPPER=true;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE     
    driver-class-name: org.h2.Driver
    username: sa                    # Default username
    password:                       # No password required for in-memory use

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect # Use H2 dialect for compatibility
    hibernate:
      ddl-auto: create-drop       # Create schema on startup, drop it on shutdown
    show-sql: true                # Log all executed SQL statements (useful for debugging)
    properties:
      hibernate:
        '[format_sql]': true      # Format SQL for easier reading in logs
        '[globally_quoted_identifiers]': false # keep "CHANGE" / "TIMESTAMP" quoted
        '[jdbc.time_zone]': UTC  # Ensure consistent timezone handling
  sql:
    init:
      mode: never

  h2:
    console:
      enabled: true               # Enable browser-based H2 console for debugging
      path: /h2-console           # Accessible at /h2-console (only in local/test environments)

logging:
  file:
    name: logs/test-application.log  # Log file for test runs
  level:
    '[org.hobernate.SQL]': DEBUG     # Detailed Hibernate SQL logging
    '[org.hibernate.type.descriptor.sql]': trace # Log SQL parameter values
    root: INFO                    # Verbose logging for test diagnostics

server:
  port: 8081                       # Ensure consistent port for testing environments

management:
  endpoints:
    web:
      exposure:
        include: health            # Allow health check exposure in test profile
  endpoint:
    health:
      show-details: always         # Always show detailed health info (for CI assertions)

# Overrides schema for H2 tests (used in @Table(schema = "$(USERS_SCHEMA:ADMIN)")) 
# warning: This is a placeholder and should be replaced with actual schema name in production.