spring:
  datasource:
    url: jdbc:oracle:thin:@sspdb_tp?TNS_ADMIN=C:/Users/carlo/Documents/githubprojects/inventory-service/oracle_wallet/Wallet_sspdb
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true
        database-platform: org.hibernate.dialect.OracleDialect
 
logging:
    level:
      root: DEBUG
    file:
      name: logs/dev-application.log
    logback:
      rollingpolicy:
        max-file-size: 10MB
        max-history: 7
server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
