
ALTER TABLE SUPPLIER
ADD CONSTRAINT FK_SUPPLIER_CREATED_BY
FOREIGN KEY (created_by) REFERENCES USERS_APP (id);

ALTER TABLE INVENTORY_ITEM
ADD CONSTRAINT FK_INVENTORY_SUPPLIER
FOREIGN KEY (supplier_id) REFERENCES SUPPLIER (id);

ALTER TABLE INVENTORY_ITEM
ADD CONSTRAINT FK_INVENTORY_CREATED_BY
FOREIGN KEY (created_by) REFERENCES USERS_APP (id);

ALTER TABLE STOCK_HISTORY
ADD CONSTRAINT FK_STOCKHISTORY_ITEM
FOREIGN KEY (item_id) REFERENCES INVENTORY_ITEM (id);

ALTER TABLE SUPPLIER_RETURN
ADD CONSTRAINT FK_SUPPLIERRETURN_ITEM
FOREIGN KEY (item_id) REFERENCES INVENTORY_ITEM (id);

ALTER TABLE SUPPLIER_RETURN
ADD CONSTRAINT FK_SUPPLIERRETURN_SUPPLIER
FOREIGN KEY (supplier_id) REFERENCES SUPPLIER (id);

ALTER TABLE SUPPLIER_RETURN
ADD CONSTRAINT FK_SUPPLIERRETURN_CREATED_BY
FOREIGN KEY (created_by) REFERENCES USERS_APP (id);

ALTER TABLE CUSTOMER_RETURN
ADD CONSTRAINT FK_CUSTOMERRETURN_ITEM
FOREIGN KEY (item_id) REFERENCES INVENTORY_ITEM (id);

ALTER TABLE CUSTOMER_RETURN
ADD CONSTRAINT FK_CUSTOMERRETURN_CREATED_BY
FOREIGN KEY (created_by) REFERENCES USERS_APP (id);

ALTER TABLE SCRAP
ADD CONSTRAINT FK_SCRAP_ITEM
FOREIGN KEY (item_id) REFERENCES INVENTORY_ITEM (id);

ALTER TABLE SCRAP
ADD CONSTRAINT FK_SCRAP_SOURCE_RETURN
FOREIGN KEY (source_return_id) REFERENCES CUSTOMER_RETURN (id);
