
CREATE TABLE USERS_APP (
  id VARCHAR2(36) PRIMARY KEY,
  email VARCHAR2(100) UNIQUE NOT NULL,
  role VARCHAR2(20) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE SUPPLIER (
  id VARCHAR2(36) PRIMARY KEY,
  name VARCHAR2(100) NOT NULL,
  contact_name VARCHAR2(100),
  phone VARCHAR2(30),
  email VARCHAR2(100),
  created_by VARCHAR2(36),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE INVENTORY_ITEM (
  id VARCHAR2(36) PRIMARY KEY,
  name VARCHAR2(100) NOT NULL,
  quantity INT NOT NULL,
  price NUMBER(10,2) NOT NULL,
  supplier_id VARCHAR2(36),
  created_by VARCHAR2(36),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE STOCK_HISTORY (
  id VARCHAR2(36) PRIMARY KEY,
  item_id VARCHAR2(36),
  change INT NOT NULL,
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  reason VARCHAR2(255)
);

CREATE TABLE SUPPLIER_RETURN (
  id VARCHAR2(36) PRIMARY KEY,
  item_id VARCHAR2(36),
  supplier_id VARCHAR2(36),
  quantity INT NOT NULL,
  return_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  reason VARCHAR2(255),
  created_by VARCHAR2(36)
);

CREATE TABLE CUSTOMER_RETURN (
  id VARCHAR2(36) PRIMARY KEY,
  item_id VARCHAR2(36),
  quantity INT NOT NULL,
  customer_name VARCHAR2(100),
  return_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  reason VARCHAR2(255),
  return_to_stock NUMBER(1) DEFAULT 0,
  is_damaged NUMBER(1) DEFAULT 0,
  created_by VARCHAR2(36)
);

CREATE TABLE SCRAP (
  id VARCHAR2(36) PRIMARY KEY,
  item_id VARCHAR2(36),
  quantity INT NOT NULL,
  scrap_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  reason VARCHAR2(255),
  source_return_id VARCHAR2(36)
);
