
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE SCRAP CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE CUSTOMER_RETURN CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE SUPPLIER_RETURN CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE STOCK_HISTORY CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE INVENTORY_ITEM CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE SUPPLIER CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE USERS_APP CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
