openapi: 3.0.3
info:
  title: SmartSupplyPro API
  version: 1.0.0
  description: >
    Source OpenAPI spec (manually maintained). The CI bundles this file
    into openapi.yaml and builds api.html (ReDoc).

servers:
  - url: https://inventoryservice.fly.dev/api
    description: Production (Fly.io)
  - url: http://localhost:8081
    description: Local dev

tags:
  - name: Analytics
    description: Read-only analytics and KPIs
  - name: Inventory
    description: CRUD and mutations for inventory items

x-tagGroups:
  - name: Analytics
    tags: [Analytics]
  - name: Inventory
    tags: [Inventory]
   
paths:
  $ref: ./paths/_index.yaml

components:
  $ref: ./components/_index.yaml

security:
  - sessionCookie: []                 # satisfied if a valid session cookie is present
  - oidc: [openid, email, profile]    # OR via Google OIDC scopes you actually request
