openapi: 3.0.3
info:
  title: SmartSupplyPro API
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  description: >
    Source OpenAPI spec (manually maintained). The CI bundles this file
    into openapi.yaml and builds api.html (ReDoc).

servers:
  - url: https://inventoryservice.fly.dev/api
    description: Production (Fly.io)

tags:
  - name: Analytics
    description: Read-only analytics and KPIs
  - name: Inventory
    description: CRUD and mutations for inventory items
  - name: Auth
    description: Authentication and profile endpoints
  - name: Health
    description: Health and monitoring endpoints
  - name: Suppliers
    description: Supplier management endpoints
  - name: Stock History
    description: Read-only historical stock change endpoints

x-tagGroups:
  - name: Analytics
    tags: [Analytics]
  - name: Inventory
    tags: [Inventory]
  - name: Stock History
    tags: ["Stock History"]
  - name: Platform & Support
    tags: [Auth, Health]
  - name: Suppliers
    tags: [Suppliers]
   
paths:
  $ref: ./paths/_index.yaml

components:
  $ref: ./components/_index.yaml

security:
  - sessionCookie: []                 # satisfied if a valid session cookie is present
  - oidc: [openid, email, profile]    # OR via Google OIDC scopes you actually request
