openapi: 3.0.3
info:
  title: SmartSupplyPro API
  version: 1.0.0
  description: >
    Source OpenAPI spec (manually maintained). The CI bundles this file
    into openapi.yaml and builds api.html (ReDoc).

servers:
  - url: https://inventoryservice.fly.dev/api
    description: Production (Fly.io)

tags:
  - name: Analytics
    description: Read-only analytics and KPIs

paths:
  /analytics/stock-value:
    $ref: ./paths/analytics/stock-value.yaml
  /analytics/stock-per-supplier:
    $ref: ./paths/analytics/stock-per-supplier.yaml
  /analytics/financial/summary:
    $ref: ./paths/analytics/financial-summary.yaml
  /analytics/price-trend:
    $ref: ./paths/analytics/price-trend.yaml
  /analytics/monthly-stock-movement:
    $ref: ./paths/analytics/monthly-stock-movement.yaml
  /analytics/summary:
    $ref: ./paths/analytics/summary.yaml
  /analytics/item-update-frequency:
    $ref: ./paths/analytics/item-update-frequency.yaml
  /analytics/low-stock-items:
    $ref: ./paths/analytics/low-stock-items.yaml




components:
  schemas:
    StockValueOverTimeDTO:
      $ref: ./components/schemas/StockValueOverTimeDTO.yaml
    StockPerSupplierDTO:
      $ref: ./components/schemas/StockPerSupplierDTO.yaml
    FinancialSummaryDTO:
      $ref: ./components/schemas/FinancialSummaryDTO.yaml
    PriceTrendDTO:
      $ref: ./components/schemas/PriceTrendDTO.yaml
    MonthlyStockMovementDTO:
      $ref: ./components/schemas/MonthlyStockMovementDTO.yaml
    StockUpdateFilterDTO:
      $ref: ./components/schemas/StockUpdateFilterDTO.yaml
    StockUpdateResultDTO:
      $ref: ./components/schemas/StockUpdateResultDTO.yaml
    DashboardSummaryDTO:
      $ref: ./components/schemas/DashboardSummaryDTO.yaml
    LowStockItemDTO:
      $ref: ./components/schemas/LowStockItemDTO.yaml
    ItemUpdateFrequencyDTO:
      $ref: ./components/schemas/ItemUpdateFrequencyDTO.yaml


