openapi: 3.0.1
info:
  title: Stock History API
  version: 1.0.0
  description: >
    Provides read-only access to historical stock changes including filtering by item, reason, and date range.
paths:
  /api/stock-history:
    get:
      summary: Get all stock history records
      description: Returns a full list of stock change records. Intended for internal use only.
      tags: [Stock History]
      responses:
        '200':
          description: A list of stock history entries
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StockHistoryDTO'

  /api/stock-history/item/{itemId}:
    get:
      summary: Get stock history by item ID
      description: Retrieves stock change records for a specific inventory item.
      tags: [Stock History]
      parameters:
        - name: itemId
          in: path
          required: true
          schema:
            type: string
          description: The inventory item ID
      responses:
        '200':
          description: Stock history for the given item
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StockHistoryDTO'

  /api/stock-history/reason/{reason}:
    get:
      summary: Get stock history by change reason
      description: Filters stock history based on the change reason (e.g., SOLD, SCRAPPED).
      tags: [Stock History]
      parameters:
        - name: reason
          in: path
          required: true
          schema:
            type: string
            enum: [RECEIVED, SOLD, SCRAPPED, RETURNED_TO_SUPPLIER, DESTROYED]
      responses:
        '200':
          description: Filtered stock history
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StockHistoryDTO'

  /api/stock-history/search:
    get:
      summary: Filter stock history
      description: >
        Performs advanced filtering with optional start and end date, item name, supplier ID. Supports pagination.
      tags: [Stock History]
      parameters:
        - in: query
          name: startDate
          schema:
            type: string
            format: date-time
        - in: query
          name: endDate
          schema:
            type: string
            format: date-time
        - in: query
          name: itemName
          schema:
            type: string
        - in: query
          name: supplierId
          schema:
            type: string
        - $ref: '#/components/parameters/Page'
        - $ref: '#/components/parameters/Size'
      responses:
        '200':
          description: Filtered and paginated stock history
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedStockHistoryDTO'

components:
  schemas:
    StockHistoryDTO:
      type: object
      properties:
        id:
          type: string
        itemId:
          type: string
        itemName:
          type: string
        changeAmount:
          type: integer
        reason:
          type: string
        timestamp:
          type: string
          format: date-time
        createdBy:
          type: string

    PagedStockHistoryDTO:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/StockHistoryDTO'
        totalElements:
          type: integer
        totalPages:
          type: integer
        size:
          type: integer
        number:
          type: integer

  parameters:
    Page:
      name: page
      in: query
      schema:
        type: integer
      description: Page number (0-based)
    Size:
      name: size
      in: query
      schema:
        type: integer
      description: Page size
