package com.smartsupplypro.inventory.dto;

import lombok.*;

import java.time.LocalDateTime;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Email;

/**
 * DTO representing a supplier entity.
 *
 * <p>Used for creating, updating, and displaying supplier data
 * via REST APIs. Includes validation to enforce basic data quality.
 *
 * <p>Typical use cases include:
 * <ul>
 *     <li>Supplier registration and editing (ADMIN-only)</li>
 *     <li>Supplier filtering and selection in inventory flows</li>
 *     <li>Audit logging and user accountability</li>
 * </ul>
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class SupplierDTO {

    /**
     * Unique identifier for the supplier.
     * Typically generated by the backend.
     */
    private String id;

    /**
     * Display name of the supplier.
     */
    @NotBlank(message = "Name is required")
    private String name;

    /**
     * Optional contact person's full name.
     */
    private String contactName;

    /**
     * Optional phone number for the supplier.
     */
    private String phone;

    /**
     * Optional email address for the supplier.
     * Must follow valid email format if provided.
     */
    @Email(message = "Invalid email format")
    private String email;

    /**
     * User who created this supplier entry.
     * Required for auditing and filtering.
     */
    @NotBlank(message = "CreatedBy must be provided.")
    private String createdBy;

    /**
     * Timestamp of when the supplier was created.
     * Usually auto-set by the backend.
     */
    private LocalDateTime createdAt;
}

