
name: Inventory Service CI/CD - CI Build & Test
# This workflow builds and tests the Inventory Service application using Maven and Docker.
# It is triggered on pushes and pull requests to the main branch.

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Enable debug output
        run: set -x

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean verify

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image (DEV)
        run: |
          docker build --build-arg PROFILE=dev -t ${{ secrets.DOCKER_USERNAME }}/inventory-service:dev .

      - name: Push Docker image (DEV)
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/inventory-service:dev
