
name: Inventory Service CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Enable debug output
        run: set -x

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: |
          set -x
          mvn clean verify

      - name: Debug Secrets
        run: |
          echo "DOCKER_USERNAME is: '${{ secrets.DOCKER_USERNAME }}'"
          echo "DOCKER_PASSWORD is set: ${{ secrets.DOCKER_PASSWORD != '' }}"
          echo "Length of DOCKER_PASSWORD: ${#DOCKER_PASSWORD}"
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        continue-on-error: false
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          set -x
          docker build --build-arg PROFILE=prod -t inventory-service:ci .

      - name: Tag & Push Docker image
        run: |
          set -x
          docker tag inventory-service:ci ${{ secrets.DOCKER_USERNAME }}/inventory-service:v1.0.0
          docker push ${{ secrets.DOCKER_USERNAME }}/inventory-service:v1.0.0
