name: Publish JaCoCo Coverage

on:
  workflow_run:
    workflows:
      - "Inventory Service CI/CD - CI Build & Test & Docker Build"
    types:
      - completed

concurrency:
  group: publish-coverage-${{ github.run_id }}
  cancel-in-progress: false

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read

    steps:
      - name: Diagnostic - show workflow_run context
        run: |
          echo "workflow_run id: ${{ github.event.workflow_run.id }}"
          echo "workflow_run run_id: ${{ github.event.workflow_run.run_id }}"
          echo "workflow_run head_branch: ${{ github.event.workflow_run.head_branch }}"

      - name: Find and download coverage artifact (robust)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail

          owner_repo="${{ github.repository }}"
          artifact_name="jacoco-coverage"

          echo "Looking up artifact '${artifact_name}' for workflow run"
          echo "workflow_run.id: ${{ github.event.workflow_run.id }}"
          echo "workflow_run.run_id: ${{ github.event.workflow_run.run_id }}"

          candidates=("${{ github.event.workflow_run.run_id }}" "${{ github.event.workflow_run.id }}")
          artifact_id=""
          artifact_url=""

          for runid in "${candidates[@]}"; do
            if [ -z "$runid" ] || [ "$runid" = "null" ]; then
              continue
            fi
            resp=$(curl -s -H "Authorization: token ${GITHUB_TOKEN}" -H "Accept: application/vnd.github+json" "https://api.github.com/repos/${owner_repo}/actions/runs/${runid}/artifacts") || true
            aid=$(echo "$resp" | jq -r --arg NAME "$artifact_name" '.artifacts[] | select(.name == $NAME) | .id' 2>/dev/null || true)
            aid_url=$(echo "$resp" | jq -r --arg NAME "$artifact_name" '.artifacts[] | select(.name == $NAME) | .archive_download_url' 2>/dev/null || true)
            if [ -n "$aid" ] && [ "$aid" != "null" ]; then
              artifact_id="$aid"
              artifact_url="$aid_url"
              echo "Found artifact '$artifact_name' (id=$artifact_id) in run $runid"
              if [ -n "$artifact_url" ] && [ "$artifact_url" != "null" ]; then
                echo "Using artifact archive_download_url: $artifact_url"
              fi
              break
            fi
          done

          if [ -z "$artifact_id" ]; then
            resp_runs=$(curl -s -H "Authorization: token ${GITHUB_TOKEN}" -H "Accept: application/vnd.github+json" "https://api.github.com/repos/${owner_repo}/actions/workflows/ci-build.yml/runs?branch=main&status=success&per_page=10") || true
            run_count=$(echo "$resp_runs" | jq -r '.workflow_runs | length')
            for i in $(seq 0 $((run_count - 1))); do
              runid=$(echo "$resp_runs" | jq -r ".workflow_runs[$i].id")
              resp2=$(curl -s -H "Authorization: token ${GITHUB_TOKEN}" -H "Accept: application/vnd.github+json" "https://api.github.com/repos/${owner_repo}/actions/runs/${runid}/artifacts") || true
              aid=$(echo "$resp2" | jq -r --arg NAME "$artifact_name" '.artifacts[] | select(.name == $NAME and .expired == false) | .id' 2>/dev/null || true)
              aid_url=$(echo "$resp2" | jq -r --arg NAME "$artifact_name" '.artifacts[] | select(.name == $NAME and .expired == false) | .archive_download_url' 2>/dev/null || true)
              if [ -n "$aid" ] && [ "$aid" != "null" ]; then
                artifact_id="$aid"
                artifact_url="$aid_url"
                echo "Found artifact '$artifact_name' (id=$artifact_id) in fallback run $runid"
                if [ -n "$artifact_url" ] && [ "$artifact_url" != "null" ]; then
                  echo "Using artifact archive_download_url: $artifact_url"
                fi
                break
              fi
            done
          fi

          if [ -z "$artifact_id" ]; then
            echo "::warning::No artifact found to download; exiting"
            exit 0
          fi

          mkdir -p coverage_tmp
          if [ -n "$artifact_url" ] && [ "$artifact_url" != "null" ]; then
            zip_url="$artifact_url"
          else
            zip_url="https://api.github.com/repos/${owner_repo}/actions/artifacts/${artifact_id}/zip"
          fi
          echo "Downloading artifact zip from: $zip_url"
          # Try several download strategies because some API endpoints return a small JSON
          # error (HTTP 415) when an Accept header is provided. Strategy order:
          # 1) no Accept header (prefer this)
          # 2) Accept: application/octet-stream
          # 3) legacy /actions/artifacts/{id}/zip without Accept header

          tried_files=()

          attempt_download() {
            local url="$1"; local out="$2"; local header_out="$3"; shift
            echo "Attempting download: $url -> $out (headers -> $header_out)"
            curl -sSL -D "$header_out" -H "Authorization: token ${GITHUB_TOKEN}" "$url" -o "$out" || true
            tried_files+=("$out")
            # print headers preview
            echo "--- $header_out ---" >&2
            sed -n '1,200p' "$header_out" || true
          }

          # primary: artifact_url (no Accept)
          attempt_download "$zip_url" "/tmp/artifact.zip" "/tmp/artifact_headers"

          # if file seems tiny or non-zip, try with Accept: application/octet-stream
          need_retry=false
          if [ -f /tmp/artifact.zip ]; then
            size=$(stat -c%s /tmp/artifact.zip)
            if [ "$size" -lt 1024 ]; then
              need_retry=true
            fi
          else
            need_retry=true
          fi

          if [ "$need_retry" = true ]; then
            echo "Primary download looks small or missing; retrying with Accept: application/octet-stream"
            curl -sSL -D /tmp/artifact_headers2 -H "Authorization: token ${GITHUB_TOKEN}" -H "Accept: application/octet-stream" "$zip_url" -o /tmp/artifact2.zip || true
            echo "--- /tmp/artifact_headers2 ---" >&2
            sed -n '1,200p' /tmp/artifact_headers2 || true
          fi

          # if still small, try legacy endpoint without Accept header
          final_file=""
          if [ -f /tmp/artifact.zip ] && [ $(stat -c%s /tmp/artifact.zip) -ge 1024 ]; then
            final_file="/tmp/artifact.zip"
          elif [ -f /tmp/artifact2.zip ] && [ $(stat -c%s /tmp/artifact2.zip) -ge 1024 ]; then
            final_file="/tmp/artifact2.zip"
          else
            echo "Retrying legacy artifacts endpoint as a last resort"
            legacy_url="https://api.github.com/repos/${owner_repo}/actions/artifacts/${artifact_id}/zip"
            curl -sSL -D /tmp/artifact_headers_legacy -H "Authorization: token ${GITHUB_TOKEN}" "$legacy_url" -o /tmp/artifact_legacy.zip || true
            echo "--- /tmp/artifact_headers_legacy ---" >&2
            sed -n '1,200p' /tmp/artifact_headers_legacy || true
            if [ -f /tmp/artifact_legacy.zip ] && [ $(stat -c%s /tmp/artifact_legacy.zip) -ge 1024 ]; then
              final_file="/tmp/artifact_legacy.zip"
            fi
          fi

          if [ -z "$final_file" ]; then
            echo "::warning::Download attempts failed or returned small payloads; showing attempted artifact list and repository-level artifacts" >&2
            for f in "${tried_files[@]}"; do
              if [ -f "$f" ]; then
                echo "$f exists size: $(stat -c%s $f) bytes" >&2
                echo "Preview (first 400 bytes):" >&2
                head -c 400 "$f" | sed -n '1,200p' || true
              fi
            done
            curl -s -H "Authorization: token ${GITHUB_TOKEN}" -H "Accept: application/vnd.github+json" "https://api.github.com/repos/${owner_repo}/actions/artifacts" | jq -C '.' || true
          else
            echo "$final_file exists, size: $(stat -c%s $final_file) bytes"
            # quick check: is this an HTML error page instead of a zip?
            if head -n 1 "$final_file" | grep -qi '<!DOCTYPE\|<html'; then
              echo "::error::Downloaded artifact looks like HTML (likely an auth/error page)." >&2
              echo "First 400 bytes of the downloaded file:" >&2
              head -c 400 "$final_file" | sed -n '1,200p' || true
            fi
            unzip -q "$final_file" -d coverage_tmp || true
            echo "Unpacked coverage_tmp/ contents:" && ls -la coverage_tmp || true
          fi

      - name: Checkout repository (main)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          ref: main

      - name: Copy coverage into main
        run: |
          set -euo pipefail
          if [ -d coverage_tmp ] && [ "$(ls -A coverage_tmp | wc -l)" -gt 0 ]; then
            mkdir -p docs/backend/coverage
            rm -rf docs/backend/coverage/* || true
            cp -r coverage_tmp/* docs/backend/coverage/ || true
            git add docs/backend/coverage/
          else
            echo "::warning::No coverage artifact found; skipping commit."
            exit 0
          fi

      - name: Commit and push coverage to main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          if git diff --cached --quiet; then
            echo "No coverage changes to commit"
          else
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git commit -m "chore(coverage): update JaCoCo site [skip ci]" || true
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:refs/heads/main
          fi
