name: Inventory Service Staging Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image (PROD)
        run: |
          docker build --build-arg PROFILE=prod -t ${{ secrets.DOCKER_USERNAME }}/inventory-service:prod .

      - name: Push Docker image (PROD)
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/inventory-service:prod
