name: Inventory Service - Staging Deploy

on:
  workflow_dispatch:  # manual trigger for now
  push:
    branches: [ "main" ]  # optional: only deploy on main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build without running tests
        run: mvn clean install -DskipTests

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image for staging
        run: docker build --build-arg PROFILE=dev -t ${{ secrets.DOCKER_USERNAME }}/inventory-service:staging .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/inventory-service:staging
